var singers = [
    "Olivia Rodrigo",
    "Sabrina Carpenter",
    "Benson Boone",
    "Nessa Barrett",
    "Tate McRae",
    "Madison Beer",
    "Joshua Bassett",
    "Billie Eilish",
    "Ariana Grande",
    "Taylor Swift",
    "Dua Lipa",
    "Justin Bieber",
    "Demi Lovato",
    "Maroon 5",
    "Reneé Rapp",
    "Dove Cameron",
    "Drex Carter",
    "Avicii",
    "Neffex",
    "Yuston XIII",
    "Orelsan",
    "T3NZU",
    "Imagine Dragons",
    "OneRepublic",
    "David Guetta",
    "TheFatRat",
    "Avril Lavigne",
    "Celine Dion",
    "Kurt Kobain",
    "Rihanna",
    "Emily Osment",
    "Ethan Cutkosky",
    "Ben Barnes",
    "Conan Grey"
]

var actors = [
    "Ariana Greenblatt",
    "Drew Starkey",
    "Jennifer Aniston",
    "Sydney Sweeney",
    "Madelyn Cline",
    "Pierre Niney",
    "Adèle Exarchopoulos",
    "Timothée Chalamet",
    "Alexandra Demi",
    "Dylan O'brien",
    "Emma Watson",
    "Will Smith",
    "Jenna Ortega",
    "Nina Dobrev",
    "Candice Accola",
    "Emily Osment",
    "Tania Raymonde",
    "Chrisopher Masteron",
    "Ethan Cutkosky",
    "Noel Fisher",
    "Emmy Rossum",
    "Emmy Kenney",
    "Shanola Hampton",
    "Eliza Taylor",
    "Bob Marley",
    "Marie Avgeropoulos",
    "Lindsey Morgan",
    "Thomas McDonell",
    "Ricky Whittle",
    "Devon Bostick",
    "Ben Barnes",
    "Andrew Garfield",
    "Chris Wood",
    "Claire Holt",
    "Joseph Morgan",
    "Seth MacFarlane",
    "Daniel Gilies",
    "Benjamin Wadsworth",
    "Phoebe Tonkin",
    "Lola Flanery",
    "Nicole Wallace",
    "Kylie Cantrall",
]

var models = [
    "Vinnie Hacker",
    "Kendall Jenner",
    "Hailey Bieber",
]

var alls = []
alls = alls.concat(singers)
alls = alls.concat(actors)
alls = alls.concat(models)