var singers = [
    "Olivia Rodrigo",
    "Sabrina Carpenter",
    "Benson Boone",
    "Nessa Barrett",
    "Tate McRae",
    "Madison Beer",
    "Joshua Bassett",
    "Billie Eilish",
    "Ariana Grande",
    "Taylor Swift",
    "Dua Lipa",
    "Justin Bieber",
    "Demi Lovato",
    "Maroon 5",
    "Reneé Rapp",
    "Dove Cameron",
    "Drex Carter",
    "Avicii",
    "Neffex",
    "Yuston XIII",
    "Orelsan",
    "T3NZU",
    "Imagine Dragons",
    "OneRepublic",
    "David Guetta",
    "TheFatRat"
]

var actors = [
    "Ariana Greenblatt",
    "Drew Starkey",
    "Jennifer Aniston",
    "Sydney Sweeney",
    "Madelyn Cline",
    "Pierre Niney",
    "Adèle Exarchopoulos",
]